=== blacksempai/JavaExternal/Projects/Project6/Devices.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="devices" type="devicesType"/>
  <xs:complexType name="typeType">
    <xs:sequence>
      <xs:element name="peripheral" type="xs:boolean"/>
      <xs:element type="xs:float" name="power"/>
      <xs:element name="group">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="IO"/>
            <xs:enumeration value="Memory"/>
            <xs:enumeration value="Main"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="port">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="USB"/>
            <xs:enumeration value="SATA"/>
            <xs:enumeration value="COM"/>
            <xs:enumeration value="None"/>
            <xs:enumeration value="LPT"/>
            <xs:enumeration value="AM4"/>
            <xs:enumeration value="PCI"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="deviceType">
    <xs:sequence>
      <xs:element type="xs:string" name="name"/>
      <xs:element name="origin">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Germany"/>
            <xs:enumeration value="China"/>
            <xs:enumeration value="America"/>
            <xs:enumeration value="Korea"/>
            <xs:enumeration value="Italy"/>
            <xs:enumeration value="Kazahstan"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="xs:short" name="price"/>
      <xs:element type="typeType" name="type"/>
      <xs:element name="critical" type="xs:boolean"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="devicesType">
    <xs:sequence>
      <xs:element type="deviceType" name="device" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== blacksempai/JavaExternal/Projects/Project6/Devices.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet href="Devices.xsl" type="text/xsl"?>
<devices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Devices.xsd">
    <device>
        <name>Raizar Mouse</name>
        <origin>Germany</origin>
        <price>949</price>
        <type>
            <peripheral>true</peripheral>
            <power>0.5</power>
            <group>IO</group>
            <port>USB</port>
        </type>
        <critical>true</critical>
    </device>
    <device>
        <name>LogiTeth Mouse</name>
        <origin>China</origin>
        <price>500</price>
        <type>
            <peripheral>true</peripheral>
            <power>0.5</power>
            <group>IO</group>
            <port>USB</port>
        </type>
        <critical>true</critical>
    </device>
    <device>
        <name>ASIS Keyboard</name>
        <origin>China</origin>
        <price>900</price>
        <type>
            <peripheral>true</peripheral>
            <power>0.6</power>
            <group>IO</group>
            <port>USB</port>
        </type>
        <critical>true</critical>
    </device>
    <device>
        <name>Hooli WebCam</name>
        <origin>America</origin>
        <price>1200</price>
        <type>
            <peripheral>true</peripheral>
            <power>1.0</power>
            <group>IO</group>
            <port>USB</port>
        </type>
        <critical>false</critical>
    </device>
    <device>
        <name>Soviet HDD</name>
        <origin>Korea</origin>
        <price>2100</price>
        <type>
            <peripheral>false</peripheral>
            <power>4.0</power>
            <group>Memory</group>
            <port>SATA</port>
        </type>
        <critical>true</critical>
    </device>
    <device>
        <name>Fast SDD</name>
        <origin>Italy</origin>
        <price>2500</price>
        <type>
            <peripheral>false</peripheral>
            <power>2.2</power>
            <group>Memory</group>
            <port>SATA</port>
        </type>
        <critical>true</critical>
    </device>
    <device>
        <name>nFast SDD</name>
        <origin>China</origin>
        <price>1500</price>
        <type>
            <peripheral>false</peripheral>
            <power>2.5</power>
            <group>Memory</group>
            <port>SATA</port>
        </type>
        <critical>true</critical>
    </device>
        <device>
        <name>LGB Display</name>
        <origin>Kazahstan</origin>
        <price>3400</price>
        <type>
            <peripheral>true</peripheral>
            <power>20</power>
            <group>IO</group>
            <port>COM</port>
        </type>
        <critical>true</critical>
    </device>
    <device>
        <name>MC Dinalds Screen</name>
        <origin>China</origin>
        <price>2500</price>
        <type>
            <peripheral>true</peripheral>
            <power>25</power>
            <group>IO</group>
            <port>COM</port>
        </type>
        <critical>true</critical>
    </device>
    <device>
        <name>Motherboard</name>
        <origin>China</origin>
        <price>3250</price>
        <type>
            <peripheral>false</peripheral>
            <power>30</power>
            <group>Main</group>
            <port>None</port>
        </type>
        <critical>true</critical>
    </device>
    <device>
        <name>Canun Scaner</name>
        <origin>China</origin>
        <price>4000</price>
        <type>
            <peripheral>true</peripheral>
            <power>140</power>
            <group>IO</group>
            <port>LPT</port>
        </type>
        <critical>false</critical>
    </device>
    <device>
        <name>Canun Printer</name>
        <origin>China</origin>
        <price>3500</price>
        <type>
            <peripheral>true</peripheral>
            <power>235</power>
            <group>IO</group>
            <port>LPT</port>
        </type>
        <critical>false</critical>
    </device>
    <device>
        <name>Indel Processor</name>
        <origin>America</origin>
        <price>4200</price>
        <type>
            <peripheral>false</peripheral>
            <power>140</power>
            <group>Main</group>
            <port>AM4</port>
        </type>
        <critical>true</critical>
    </device>
    <device>
        <name>Mvidia Graphic Card</name>
        <origin>China</origin>
        <price>5199</price>
        <type>
            <peripheral>false</peripheral>
            <power>55</power>
            <group>Main</group>
            <port>PCI</port>
        </type>
        <critical>true</critical>
    </device>
</devices>
